from __future__ import annotations

from typing import Set


# Application types supported by Gemini File Search
GEMINI_APPLICATION_MIMES: Set[str] = {
    "application/dart",
    "application/ecmascript",
    "application/json",
    "application/ms-java",
    "application/msword",
    "application/pdf",
    "application/sql",
    "application/typescript",
    "application/vnd.curl",
    "application/vnd.dart",
    "application/vnd.ibm.secure-container",
    "application/vnd.jupyter",
    "application/vnd.ms-excel",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "application/x-csh",
    "application/x-hwp",
    "application/x-hwp-v5",
    "application/x-latex",
    "application/x-php",
    "application/x-powershell",
    "application/x-sh",
    "application/x-shellscript",
    "application/x-tex",
    "application/x-zsh",
    "application/xml",
    "application/zip",
}


# Text types supported by Gemini File Search
GEMINI_TEXT_MIMES: Set[str] = {
    "text/1d-interleaved-parityfec",
    "text/red",
    "text/sgml",
    "text/cache-manifest",
    "text/calendar",
    "text/cql",
    "text/cql-extension",
    "text/cql-identifier",
    "text/css",
    "text/csv",
    "text/csv-schema",
    "text/dns",
    "text/encaprtp",
    "text/enriched",
    "text/example",
    "text/fhirpath",
    "text/flexfec",
    "text/fwdred",
    "text/gff3",
    "text/grammar-ref-list",
    "text/hl7v2",
    "text/html",
    "text/javascript",
    "text/jcr-cnd",
    "text/jsx",
    "text/markdown",
    "text/mizar",
    "text/n3",
    "text/parameters",
    "text/parityfec",
    "text/php",
    "text/plain",
    "text/provenance-notation",
    "text/prs.fallenstein.rst",
    "text/prs.lines.tag",
    "text/prs.prop.logic",
    "text/raptorfec",
    "text/rfc822-headers",
    "text/rtf",
    "text/rtp-enc-aescm128",
    "text/rtploopback",
    "text/rtx",
    "text/shaclc",
    "text/shex",
    "text/spdx",
    "text/strings",
    "text/t140",
    "text/tab-separated-values",
    "text/texmacs",
    "text/troff",
    "text/tsv",
    "text/tsx",
    "text/turtle",
    "text/ulpfec",
    "text/uri-list",
    "text/vcard",
    "text/vnd.dmclientscript",
    "text/vnd.iptc.nitf",
    "text/vnd.iptc.newsml",
    "text/vnd.a",
    "text/vnd.abc",
    "text/vnd.ascii-art",
    "text/vnd.curl",
    "text/vnd.debian.copyright",
    "text/vnd.dvb.subtitle",
    "text/vnd.esmertec.theme-descriptor",
    "text/vnd.exchangeable",
    "text/vnd.familysearch.gedcom",
    "text/vnd.ficlab.flt",
    "text/vnd.fly",
    "text/vnd.fmi.flexstor",
    "text/vnd.gml",
    "text/vnd.graphviz",
    "text/vnd.hans",
    "text/vnd.hgl",
    "text/vnd.in3d.3dml",
    "text/vnd.in3d.spot",
    "text/vnd.latex-z",
    "text/vnd.motorola.reflex",
    "text/vnd.ms-mediapackage",
    "text/vnd.net2phone.commcenter.command",
    "text/vnd.radisys.msml-basic-layout",
    "text/vnd.senx.warpscript",
    "text/vnd.sosi",
    "text/vnd.sun.j2me.app-descriptor",
    "text/vnd.trolltech.linguist",
    "text/vnd.wap.si",
    "text/vnd.wap.sl",
    "text/vnd.wap.wml",
    "text/vnd.wap.wmlscript",
    "text/vtt",
    "text/wgsl",
    "text/x-asm",
    "text/x-bibtex",
    "text/x-boo",
    "text/x-c",
    "text/x-c++hdr",
    "text/x-c++src",
    "text/x-cassandra",
    "text/x-chdr",
    "text/x-coffeescript",
    "text/x-component",
    "text/x-csh",
    "text/x-csharp",
    "text/x-csrc",
    "text/x-cuda",
    "text/x-d",
    "text/x-diff",
    "text/x-dsrc",
    "text/x-emacs-lisp",
    "text/x-erlang",
    "text/x-gff3",
    "text/x-go",
    "text/x-haskell",
    "text/x-java",
    "text/x-java-properties",
    "text/x-java-source",
    "text/x-kotlin",
    "text/x-lilypond",
    "text/x-lisp",
    "text/x-literate-haskell",
    "text/x-lua",
    "text/x-moc",
    "text/x-objcsrc",
    "text/x-pascal",
    "text/x-pcs-gcd",
    "text/x-perl",
    "text/x-perl-script",
    "text/x-python",
    "text/x-python-script",
    "text/x-r-markdown",
    "text/x-rsrc",
    "text/x-rst",
    "text/x-ruby-script",
    "text/x-rust",
    "text/x-sass",
    "text/x-scala",
    "text/x-scheme",
    "text/x-script.python",
    "text/x-scss",
    "text/x-setext",
    "text/x-sfv",
    "text/x-sh",
    "text/x-siesta",
    "text/x-sos",
    "text/x-sql",
    "text/x-swift",
    "text/x-tcl",
    "text/x-tex",
    "text/x-vbasic",
    "text/x-vcalendar",
    "text/xml",
    "text/xml-dtd",
    "text/xml-external-parsed-entity",
    "text/yaml",
}


GEMINI_SUPPORTED_MIMES: Set[str] = GEMINI_APPLICATION_MIMES | GEMINI_TEXT_MIMES


# Upload profiles -------------------------------------------------------------

SAFE_DEFAULT_UPLOAD_MIMES: Set[str] = {
    "application/pdf",
    "text/plain",
    "text/markdown",
    "text/csv",
    "text/tab-separated-values",
}

OFFICE_UPLOAD_MIMES: Set[str] = SAFE_DEFAULT_UPLOAD_MIMES | {
    "application/msword",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
}

ALL_SUPPORTED_UPLOAD_MIMES: Set[str] = GEMINI_SUPPORTED_MIMES
